### ISSUE TITLE
need support HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by dekhtyarev** [2gis/k8s-handle#11]
Now, we have error:
```
ERROR:__main__:RuntimeError: Unknown kind "HorizontalPodAutoscaler" in generated file
ERROR: Job failed: exit code 1
```

Example manifest:
```
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ app_name }}
spec:
  maxReplicas: {{ hpa_max_replicas }}
  minReplicas: {{ hpa_min_replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ app_name }}
  targetCPUUtilizationPercentage: 70
```
