### ISSUE TITLE
skip-tags does not work

### ISSUE THREAD

**Issue by sepich** [2gis/k8s-handle#119]
Hello,
it seems `--skip-tags` does not work. Steps to reproduce:
```
git clone git@github.com:2gis/k8s-handle-example.git
```
Edit config.yaml, add some tag
```
staging:
  templates:
  - template: configmap.yaml.j2
  - template: deployment.yaml.j2
  - template: service.yaml.j2
    tags: manual
```
Render is empty:
```
$ docker run --rm -v `pwd`:/tmp -w /tmp 2gis/k8s-handle k8s-handle render -s staging --skip-tags manual

                         _(_)_                          wWWWw   _
             @@@@       (_)@(_)   vVVVv     _     @@@@  (___) _(_)_
            @@()@@ wWWWw  (_)\    (___)   _(_)_  @@()@@   Y  (_)@(_)
             @@@@  (___)     `|/    Y    (_)@(_)  @@@@   \|/   (_)
              /      Y       \|    \|/    /(_)    \|      |/      |
           \ |     \ |/       | / \ | /  \|/       |/    \|      \|/
            \|//    \|///    \|//  \|/// \|///    \|//    |//    \|//
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
