### ISSUE TITLE
Multiple Kubernetes resources per template file

### ISSUE THREAD

**Issue by seleznev** [2gis/k8s-handle#58]
k8s-handle expects only one YAML documents per template file and throw an exception if found more:

```
2018-10-31 05:33:28 ERROR:__main__:RuntimeError: Unable to load yaml file: /tmp/k8s-handle/namespace.yaml, expected a single document in the stream
  in "<unicode string>", line 4, column 1:
    kind: Namespace
    ^
but found another document
  in "<unicode string>", line 7, column 1:
    ---
    ^
```

Multiple resources per template will be useful when you want to create many similar resources like namespaces, resource quotas, role bindings.

For example:

* `config.yaml`:
```yaml
common:
  k8s_master_uri: "{{ env='K8S_MASTER_URI' }}"
  k8s_token: "{{ env='K8S_TOKEN' }}"
  k8s_ca_base64: "{{ env='K8S_CA_BASE64' }}"

testing:
  kubectl:
  - template: namespaces.yaml.j2

  namespaces:
  - first
  - second
  - third
```
* `templates/namespaces.yaml.j2`:
```jinja2
{% for namespace in namespaces %}
---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
{% endfor %}
```
