### ISSUE TITLE
Add CustomResourceDefinition kind support

### ISSUE THREAD

**Issue by seleznev** [2gis/k8s-handle#85]
k8s-handle doesn't support [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/) yet:

```
2019-02-13 04:05:19 ERROR:k8s_handle:RuntimeError: Unknown kind "CustomResourceDefinition" in generated file
```

API group:

```
$ kubectl api-resources --api-group=apiextensions.k8s.io
NAME                        SHORTNAMES   APIGROUP               NAMESPACED   KIND
customresourcedefinitions   crd,crds     apiextensions.k8s.io   false        CustomResourceDefinition
```

Example ([link](https://github.com/jetstack/cert-manager/blob/master/deploy/manifests/00-crds.yaml)):
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.certmanager.k8s.io
  labels:
    app: cert-manager
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .spec.secretName
    name: Secret
    type: string
  - JSONPath: .spec.issuerRef.name
    name: Issuer
    type: string
    priority: 1
  - JSONPath: .status.conditions[?(@.type=="Ready")].message
    name: Status
    type: string
    priority: 1
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: certmanager.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Certificate
    plural: certificates
    shortNames:
    - cert
    - certs
```
