### ISSUE TITLE
Add custom resources support

### ISSUE THREAD

**Issue by seleznev** [2gis/k8s-handle#86]
After #85 will be done we will want to deploy our [custom resources](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-custom-objects) too.

Example ([link](https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/index.html#creating-certificate-resources)):
```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
spec:
  secretName: example-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: example.com
  dnsNames:
  - example.com
  - www.example.com
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
```
